#!/usr/bin/env node
/**
 * Turn the Google Fonts CSS in fonts/src/gf.css into fonts/fonts.css, with
 * every woff2 inlined as a data: URI.
 *
 * Why inline rather than link: Obsidian is offline-first. A theme that fetches
 * fonts from a CDN on every launch leaks the user's IP to a third party and
 * stalls startup when they have no connection. Inlining costs file size and
 * buys a theme that is genuinely self-contained.
 *
 * Only the subsets in KEEP_SUBSETS are kept. Everything Google emits for these
 * families (devanagari, vietnamese, greek) would multiply the file size for
 * coverage the theme's users are unlikely to need — and the fallback stack
 * still handles those glyphs, just in a different face.
 *
 * Run: node scripts/build-fonts.js
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "fonts", "src", "gf.css");
const OUT = join(ROOT, "fonts", "fonts.css");

/* Google labels each @font-face block with a `/* subset *​/` comment above it. */
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

const css = readFileSync(SRC, "utf8");

/* Split on the subset comments so each face keeps its label. */
const chunks = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1);
const faces = [];
for (let i = 0; i < chunks.length; i += 2) {
  const subset = chunks[i];
  const block = chunks[i + 1];
  if (!KEEP_SUBSETS.has(subset)) continue;
  const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  if (!url) continue;
  faces.push({
    subset,
    url,
    family: /font-family:\s*'([^']+)'/.exec(block)?.[1],
    weight: /font-weight:\s*(\d+)/.exec(block)?.[1] ?? "400",
    style: /font-style:\s*(\w+)/.exec(block)?.[1] ?? "normal",
    unicodeRange: /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim(),
  });
}

if (faces.length === 0) {
  console.error("No faces matched. Did fonts/src/gf.css download correctly?");
  process.exit(1);
}

const out = [
  "/* Generated by scripts/build-fonts.js — do not edit by hand.",
  " *",
  " * Orbitron, Rajdhani, and Share Tech Mono are licensed under the SIL Open",
  " * Font License 1.1, which permits redistribution inside this theme. The",
  " * full licence text is in fonts/OFL.txt.",
  " */",
  "",
];

let total = 0;
for (const face of faces) {
  const response = await fetch(face.url);
  if (!response.ok) {
    console.error(`${face.url} -> HTTP ${response.status}`);
    process.exit(1);
  }
  const bytes = Buffer.from(await response.arrayBuffer());
  total += bytes.length;
  console.log(
    `${face.family} ${face.weight} ${face.subset}`.padEnd(40) +
      `${(bytes.length / 1024).toFixed(1)} KB`,
  );

  out.push(
    "@font-face {",
    `  font-family: '${face.family}';`,
    `  font-style: ${face.style};`,
    `  font-weight: ${face.weight};`,
    "  font-display: swap;",
    `  src: url(data:font/woff2;base64,${bytes.toString("base64")}) format('woff2');`,
    face.unicodeRange ? `  unicode-range: ${face.unicodeRange};` : "",
    "}",
    "",
  );
}

if (!existsSync(dirname(OUT))) mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out.filter((line) => line !== "").join("\n") + "\n");

const written = readFileSync(OUT).length;
console.log(
  `\n${faces.length} faces, ${(total / 1024).toFixed(1)} KB of font data ` +
    `-> ${(written / 1024).toFixed(1)} KB of CSS (base64 costs ~33%).`,
);
